# Build setup for Travis CI

language:
  - java

jdk:
  - oraclejdk8

os:
  - linux

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - ./mvn clean package -Dheadless=true

after_success:
  - bash <(curl -s https://codecov.io/bash)